[package]
name = "cli-app"
version = "0.1.0"
authors = ["相田 優希 <51500566+aida0710@users.noreply.github.com>"]
edition = "2018"

[dependencies]
pcap = {version = "2.0.0"}
ratatui = {version = "0.27.0"}